/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdministratorPage: typeof import('./src/components/administratorPage.vue')['default']
    Banner: typeof import('./src/components/banner.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    LoginNRegister: typeof import('./src/components/loginNRegister.vue')['default']
    MainPage: typeof import('./src/components/mainPage.vue')['default']
    ManageProductPage: typeof import('./src/components/manageProductPage.vue')['default']
    OrderListPage: typeof import('./src/components/orderListPage.vue')['default']
    OrderListPageAgain: typeof import('./src/components/orderListPageAgain.vue')['default']
    ProductAdminList: typeof import('./src/components/productAdminList.vue')['default']
    ProductCard: typeof import('./src/components/productCard.vue')['default']
    ProductDetailPage: typeof import('./src/components/productDetailPage.vue')['default']
    ReviewCard: typeof import('./src/components/reviewCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPage: typeof import('./src/components/searchPage.vue')['default']
    ShippingPage: typeof import('./src/components/shippingPage.vue')['default']
    Showcase: typeof import('./src/components/showcase.vue')['default']
    ThumbnailProductCard: typeof import('./src/components/thumbnailProductCard.vue')['default']
    UserPage: typeof import('./src/components/userPage.vue')['default']
    UserProfileEditPage: typeof import('./src/components/userProfileEditPage.vue')['default']
  }
}
